version: '3.3'
services:

  bot:
    build: .
    volumes:
      - ./:/app/
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    command: |
      python bot.py

  redis:
    image: redis:latest

  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    command: |
      python server.py